name: Integration Tests

on:
  - pull_request

jobs:
  build:
    name: Run Integration tests
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      # Install your dependencies
      - run: npm ci

      - run: mkdir env
      - run: touch env/env.local.ts
      - run: touch env/env.dev.ts
      - run: touch env/env.prod.ts

      # Run tests
      - run: npm run test

      # Clean
      - run: rm -rf env
